create table if not exists public.community_goal (
    id bigint generated by default as identity primary key,
    daily_target integer not null default 200 check (daily_target > 0),
    current_progress integer not null default 0 check (current_progress >= 0),
    date date not null unique,
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.community_goal enable row level security;

create policy "Community goal read"
    on public.community_goal
    for select
    using (true);

create index if not exists idx_community_goal_date on public.community_goal(date desc);
