create table if not exists public.daily_feature (
    id bigint generated by default as identity primary key,
    submission_id bigint not null references public.submissions(id) on delete cascade,
    date date not null unique,
    created_at timestamptz not null default now()
);

create index if not exists idx_daily_feature_date_desc on public.daily_feature(date desc);
create index if not exists idx_daily_feature_submission_id on public.daily_feature(submission_id);

alter table public.daily_feature enable row level security;

create policy "Daily feature read"
    on public.daily_feature
    for select
    using (true);

create policy "Daily feature service role manage"
    on public.daily_feature
    for all
    using (auth.role() = 'service_role')
    with check (auth.role() = 'service_role');
