-- ═══════════════════════════════════════════════════════════════════════════
-- أجر لا ينقطع — Migration 010
-- Atomic counters, RLS fixes, index, and constraint updates
-- Safe to run multiple times (idempotent and robust)
-- ═══════════════════════════════════════════════════════════════════════════

-- ═══════════════════════════════════════════════════════════════════════════
-- 0. ROBUST TABLE & COLUMN PROVISIONING
-- ═══════════════════════════════════════════════════════════════════════════

-- community_stats
CREATE TABLE IF NOT EXISTS public.community_stats (
    id integer PRIMARY KEY DEFAULT 1,
    CONSTRAINT community_stats_single_row CHECK (id = 1)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_stats' AND column_name='total_approved') THEN
        ALTER TABLE public.community_stats ADD COLUMN total_approved integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_stats' AND column_name='total_post_count') THEN
        ALTER TABLE public.community_stats ADD COLUMN total_post_count integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_stats' AND column_name='average_post_count') THEN
        ALTER TABLE public.community_stats ADD COLUMN average_post_count numeric NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_stats' AND column_name='new_approved_today') THEN
        ALTER TABLE public.community_stats ADD COLUMN new_approved_today integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_stats' AND column_name='last_reset_date') THEN
        ALTER TABLE public.community_stats ADD COLUMN last_reset_date date NOT NULL DEFAULT CURRENT_DATE;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_stats' AND column_name='updated_at') THEN
        ALTER TABLE public.community_stats ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
    END IF;
END $$;

INSERT INTO public.community_stats (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
ALTER TABLE public.community_stats ENABLE ROW LEVEL SECURITY;

-- community_goal
CREATE TABLE IF NOT EXISTS public.community_goal (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL UNIQUE
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_goal' AND column_name='daily_target') THEN
        ALTER TABLE public.community_goal ADD COLUMN daily_target integer NOT NULL DEFAULT 100;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_goal' AND column_name='current_progress') THEN
        ALTER TABLE public.community_goal ADD COLUMN current_progress integer NOT NULL DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_goal' AND column_name='hint') THEN
        ALTER TABLE public.community_goal ADD COLUMN hint text;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_goal' AND column_name='created_at') THEN
        ALTER TABLE public.community_goal ADD COLUMN created_at timestamptz NOT NULL DEFAULT now();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='community_goal' AND column_name='updated_at') THEN
        ALTER TABLE public.community_goal ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_community_goal_date ON public.community_goal(date DESC);
ALTER TABLE public.community_goal ENABLE ROW LEVEL SECURITY;

-- daily_feature
CREATE TABLE IF NOT EXISTS public.daily_feature (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date NOT NULL UNIQUE,
    submission_id uuid NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_daily_feature_date ON public.daily_feature(date DESC);
ALTER TABLE public.daily_feature ENABLE ROW LEVEL SECURITY;

-- rate_limits (using ip_hash to match shared.js)
CREATE TABLE IF NOT EXISTS public.rate_limits (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='rate_limits' AND column_name='ip_hash') THEN
        ALTER TABLE public.rate_limits ADD COLUMN ip_hash text NOT NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='rate_limits' AND column_name='created_at') THEN
        ALTER TABLE public.rate_limits ADD COLUMN created_at timestamptz NOT NULL DEFAULT now();
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_rate_limits_ip_hash ON public.rate_limits(ip_hash);
ALTER TABLE public.rate_limits ENABLE ROW LEVEL SECURITY;

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. ATOMIC COUNTER RPCs (fixes C-2: race conditions)
-- ═══════════════════════════════════════════════════════════════════════════

-- Atomic view increment
CREATE OR REPLACE FUNCTION public.increment_view(p_submission_id uuid)
RETURNS integer
LANGUAGE sql
VOLATILE
SECURITY DEFINER
AS $$
    UPDATE public.submissions
    SET views = views + 1
    WHERE id = p_submission_id
      AND status IN ('Approved', 'Posted')
    RETURNING views;
$$;

-- Atomic post_count increment
CREATE OR REPLACE FUNCTION public.increment_post_count(p_submission_id uuid)
RETURNS integer
LANGUAGE sql
VOLATILE
SECURITY DEFINER
AS $$
    UPDATE public.submissions
    SET post_count = post_count + 1,
        last_posted_at = now()
    WHERE id = p_submission_id
      AND status IN ('Approved', 'Posted')
    RETURNING post_count;
$$;

-- Atomic goal progress increment
CREATE OR REPLACE FUNCTION public.increment_goal_progress(p_date date, p_amount integer DEFAULT 1)
RETURNS integer
LANGUAGE sql
VOLATILE
SECURITY DEFINER
AS $$
    UPDATE public.community_goal
    SET current_progress = current_progress + p_amount,
        updated_at = timezone('utc', now())
    WHERE date = p_date
    RETURNING current_progress;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. DATABASE-BACKED VIEW THROTTLING
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.view_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_hash text NOT NULL,
    submission_id uuid NOT NULL REFERENCES public.submissions(id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_view_events_lookup
    ON public.view_events(ip_hash, submission_id, created_at DESC);

ALTER TABLE public.view_events ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE tablename = 'view_events'
          AND policyname = 'View events service role manage'
    ) THEN
        CREATE POLICY "View events service role manage"
            ON public.view_events
            FOR ALL
            USING (auth.role() = 'service_role')
            WITH CHECK (auth.role() = 'service_role');
    END IF;
END $$;

-- Atomic view increment with database-backed deduplication
CREATE OR REPLACE FUNCTION public.record_and_increment_view(
    p_submission_id uuid,
    p_ip_hash text,
    p_debounce_seconds integer DEFAULT 60
)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
AS $$
DECLARE
    v_cutoff timestamptz;
    v_exists boolean;
    v_views integer;
BEGIN
    v_cutoff := now() - (p_debounce_seconds || ' seconds')::interval;

    SELECT EXISTS(
        SELECT 1 FROM public.view_events
        WHERE ip_hash = p_ip_hash
          AND submission_id = p_submission_id
          AND created_at > v_cutoff
    ) INTO v_exists;

    IF v_exists THEN
        RETURN jsonb_build_object('recorded', false, 'reason', 'debounced');
    END IF;

    INSERT INTO public.view_events (ip_hash, submission_id)
    VALUES (p_ip_hash, p_submission_id);

    UPDATE public.submissions
    SET views = views + 1
    WHERE id = p_submission_id
      AND status IN ('Approved', 'Posted')
    RETURNING views INTO v_views;

    IF v_views IS NULL THEN
        RETURN jsonb_build_object('recorded', false, 'reason', 'not_found');
    END IF;

    RETURN jsonb_build_object('recorded', true, 'views', v_views);
END;
$$;

-- Cleanup function for old view events
CREATE OR REPLACE FUNCTION public.cleanup_view_events(p_older_than_hours integer DEFAULT 24)
RETURNS integer
LANGUAGE sql
VOLATILE
SECURITY DEFINER
AS $$
    WITH deleted AS (
        DELETE FROM public.view_events
        WHERE created_at < now() - (p_older_than_hours || ' hours')::interval
        RETURNING 1
    )
    SELECT count(*)::integer FROM deleted;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. FIX STATUS CHECK CONSTRAINT
-- ═══════════════════════════════════════════════════════════════════════════

DO $$
DECLARE
    existing_constraint_name text;
BEGIN
    SELECT conname INTO existing_constraint_name
    FROM pg_constraint
    WHERE conrelid = 'public.submissions'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%status%'
    LIMIT 1;

    IF existing_constraint_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE public.submissions DROP CONSTRAINT %I', existing_constraint_name);
    END IF;

    ALTER TABLE public.submissions
        ADD CONSTRAINT submissions_status_check
        CHECK (status IN ('Pending', 'Approved', 'Rejected', 'Posted'));
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. ADD MISSING INDEXES
-- ═══════════════════════════════════════════════════════════════════════════

CREATE INDEX IF NOT EXISTS idx_submissions_visible_created
    ON public.submissions(created_at DESC)
    WHERE status IN ('Approved', 'Posted');

CREATE INDEX IF NOT EXISTS idx_submissions_visible_post_count
    ON public.submissions(post_count DESC, created_at DESC)
    WHERE status IN ('Approved', 'Posted');

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. FIX RLS POLICY GAPS
-- ═══════════════════════════════════════════════════════════════════════════

-- community_goal
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'community_goal' AND policyname = 'Community goal public read') THEN
        CREATE POLICY "Community goal public read" ON public.community_goal FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'community_goal' AND policyname = 'Community goal service role manage') THEN
        CREATE POLICY "Community goal service role manage" ON public.community_goal FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
    END IF;
END $$;

-- community_stats
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'community_stats' AND policyname = 'Community stats read') THEN
        CREATE POLICY "Community stats read" ON public.community_stats FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'community_stats' AND policyname = 'Community stats service role manage') THEN
        CREATE POLICY "Community stats service role manage" ON public.community_stats FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
    END IF;
END $$;

-- daily_feature
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'daily_feature' AND policyname = 'Daily feature public read') THEN
        CREATE POLICY "Daily feature public read" ON public.daily_feature FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'daily_feature' AND policyname = 'Daily feature service role manage') THEN
        CREATE POLICY "Daily feature service role manage" ON public.daily_feature FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
    END IF;
END $$;

-- rate_limits
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'rate_limits' AND policyname = 'Rate limits service role manage') THEN
        CREATE POLICY "Rate limits service role manage" ON public.rate_limits FOR ALL USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');
    END IF;
END $$;

-- submissions
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'submissions' AND policyname = 'Submissions public visible read') THEN
        CREATE POLICY "Submissions public visible read" ON public.submissions FOR SELECT USING (status IN ('Approved', 'Posted'));
    END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. BACKFILL MESSAGE HASHES to SHA-256
-- ═══════════════════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS pgcrypto;

UPDATE public.submissions
SET message_hash = encode(digest(message, 'sha256'), 'hex')
WHERE message_hash IS NOT NULL
  AND length(message_hash) = 32;

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. GRANT EXECUTE
-- ═══════════════════════════════════════════════════════════════════════════

GRANT EXECUTE ON FUNCTION public.record_and_increment_view(uuid, text, integer) TO anon;
GRANT EXECUTE ON FUNCTION public.increment_post_count(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.increment_goal_progress(date, integer) TO anon;
GRANT EXECUTE ON FUNCTION public.increment_view(uuid) TO anon;
GRANT EXECUTE ON FUNCTION public.cleanup_view_events(integer) TO anon;
